# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 Alexander Corrado
name: SDK Request
description: Request support for other AI SDK
title: "SDK Request: "
labels: enhancement, SDK
body:
  - type: input
    attributes:
      label: "I'd like to request support for"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Resources to support my request"
      description: "(e.g. documentation, articles, posts, etc)"
  - type: checkboxes
    attributes:
      label: ""
      options:
        - label: "I couldn't find any [other requests](https://github.com/chkn/evalution/issues?q=state%3Aopen%20label%3ASDK) for this"
          description: "(if you do, please upvote the existing issue with 👍 instead of opening a new one)"
          required: true
        - label: "I'm willing to help implement this"
        - label: "I'm willing to help test this"
