// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Alexander Corrado

/**
 * Writes the adapters' probe fallbacks: what their project probes resolve to
 * against the installed SDKs, for use when they can't be resolved at run time
 * (no checker, SDK not installed).
 *
 * - `src/sdk/typesafe-sdk/fallback.ts`, from `@typesafe-ai/sdk`
 * - `src/sdk/vercel-ai-sdk/evaluation-fallback.ts`, from `ai`
 *
 * Generated rather than hand-written so they can't drift from the SDKs'
 * types; each has a `fallback.test.ts` that fails when it does.
 *
 * Usage: `node scripts/generate-probe-fallbacks.ts`, after upgrading an SDK.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { LocalFileProvider } from "../src/file-provider-local.ts";
import type { TypeProbe } from "../src/prompt/file/prompt-file-type.ts";
import { TSPromptFileType } from "../src/prompt/file/ts/ts-prompt-file-type.ts";
import { TYPESAFE_PROJECT_PROBES } from "../src/sdk/typesafe-sdk/probes.ts";
import { EVALUATION_PROJECT_PROBES } from "../src/sdk/vercel-ai-sdk/evaluation.ts";

const ROOT = join(import.meta.dirname, "..");

const UNDEFINED = "__undefined__";

/**
 * `value` as a TypeScript literal. JSON would drop an `undefined` property —
 * and the `undefined` constant type is `{ kind: "constant", value: undefined }`,
 * which needs its `value` to type-check.
 */
function toSource(value: unknown): string {
  return JSON.stringify(
    value,
    (_key, v) => (v === undefined ? UNDEFINED : v),
    2,
  ).replaceAll(`"${UNDEFINED}"`, "undefined");
}
const fileType = new TSPromptFileType(new LocalFileProvider());

async function writeFallback({
  out,
  name,
  description,
  probes,
  pkg,
}: {
  out: string;
  name: string;
  description: string;
  probes: TypeProbe[];
  pkg: string;
}) {
  const { project } = await fileType.resolveTypes({
    project: { rootDir: ROOT, probes },
  });
  for (const [probe, result] of Object.entries(project ?? {})) {
    if (result === undefined)
      throw new Error(`Probe "${probe}" did not resolve`);
  }
  const version = (
    await import(`${pkg}/package.json`, { with: { type: "json" } })
  ).default.version;
  const path = join(ROOT, out);
  writeFileSync(
    path,
    `// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Alexander Corrado

// Generated by scripts/generate-probe-fallbacks.ts from ${pkg}@${version}.
// Do not edit by hand.

import type { ProbeResults } from "../../prompt/file/prompt-file-type.ts";

/** ${description} */
export const ${name}: ProbeResults = ${toSource(project)};
`,
  );
  // Formatted as the repo formats it, so a regeneration diffs only by content.
  execFileSync("npx", ["biome", "format", "--write", path], {
    stdio: "ignore",
  });
  console.log(`Wrote ${path}`);
}

await writeFallback({
  out: "src/sdk/typesafe-sdk/fallback.ts",
  name: "TYPESAFE_FALLBACK",
  description:
    "What the TypeSafe project probes resolve to, for when they can't be resolved.",
  probes: TYPESAFE_PROJECT_PROBES,
  pkg: "@typesafe-ai/sdk",
});

await writeFallback({
  out: "src/sdk/vercel-ai-sdk/evaluation-fallback.ts",
  name: "VERCEL_EVALUATION_FALLBACK",
  description:
    "What the Vercel AI SDK's evaluation probes resolve to, for when they can't be resolved.",
  probes: EVALUATION_PROJECT_PROBES,
  pkg: "ai",
});
