// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Alexander Corrado

/**
 * Writes `src/sdk/typesafe-sdk/fallback.ts`: what the TypeSafe adapter's
 * project probes resolve to against the installed `@typesafe-ai/sdk`, for use
 * when they can't be resolved at run time (no checker, SDK not installed).
 *
 * Generated rather than hand-written so it can't drift from the SDK's types;
 * `src/sdk/typesafe-sdk/fallback.test.ts` fails when it does.
 *
 * Usage: `node scripts/generate-typesafe-fallback.ts`, after upgrading the SDK.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { LocalFileProvider } from "../src/file-provider-local.ts";
import { TSPromptFileType } from "../src/prompt/file/ts/ts-prompt-file-type.ts";
import { TYPESAFE_PROJECT_PROBES } from "../src/sdk/typesafe-sdk/probes.ts";

const ROOT = join(import.meta.dirname, "..");
const OUT = join(ROOT, "src/sdk/typesafe-sdk/fallback.ts");

const fileType = new TSPromptFileType(new LocalFileProvider());
const { project } = await fileType.resolveTypes({
  project: { rootDir: ROOT, probes: TYPESAFE_PROJECT_PROBES },
});
for (const [name, result] of Object.entries(project ?? {})) {
  if (result === undefined) throw new Error(`Probe "${name}" did not resolve`);
}

const version = (
  await import("@typesafe-ai/sdk/package.json", { with: { type: "json" } })
).default.version;

writeFileSync(
  OUT,
  `// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Alexander Corrado

// Generated by scripts/generate-typesafe-fallback.ts from @typesafe-ai/sdk@${version}.
// Do not edit by hand.

import type { ProbeResults } from "../../prompt/file/prompt-file-type.ts";

/** What the TypeSafe project probes resolve to, for when they can't be resolved. */
export const TYPESAFE_FALLBACK: ProbeResults = ${JSON.stringify(project, null, 2)};
`,
);
console.log(`Wrote ${OUT}`);
